-- CreateTable
CREATE TABLE "AggregatedInteropTransfer" (
    "timestamp" TIMESTAMP(6) NOT NULL,
    "id" VARCHAR(255) NOT NULL,
    "srcChain" VARCHAR(255),
    "dstChain" VARCHAR(255),
    "srcAbstractTokenId" VARCHAR(255),
    "dstAbstractTokenId" VARCHAR(255),
    "transferCount" INTEGER NOT NULL,
    "totalDurationSum" INTEGER NOT NULL,
    "srcValueUsd" REAL,
    "dstValueUsd" REAL
);

-- [NOT GENERATED BY PRISMA] I added this index manually because Prisma doesn't support unique indexes on partial fields.
CREATE UNIQUE INDEX aggregated_interop_transfer_pkey 
ON "AggregatedInteropTransfer" (
  timestamp, 
  id, 
  COALESCE("srcChain", '_'), 
  COALESCE("dstChain", '_'),
  COALESCE("srcAbstractTokenId", '_'),
  COALESCE("dstAbstractTokenId", '_')
);

-- CreateIndex
CREATE UNIQUE INDEX "AggregatedInteropTransfer_id_srcChain_dstChain_srcAbstractT_key" ON "AggregatedInteropTransfer"("id", "srcChain", "dstChain", "srcAbstractTokenId", "dstAbstractTokenId");
